language: generic
sudo: required
dist: xenial
before_install:
    - curl -L -o /tmp/travis-tool.sh http://raw.github.com/StuartWheater/r-travis/master/scripts/travis-tool.sh
    - chmod 755 /tmp/travis-tool.sh
    - wget -nv https://apt.puppetlabs.com/puppet5-release-xenial.deb
    - sudo dpkg -i puppet5-release-xenial.deb
    - sudo apt-get install -qq -f
    - sudo rm -f puppet5-release-xenial.deb
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
    - sudo add-apt-repository 'deb https://dl.bintray.com/obiba/deb all main'
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
    - sudo add-apt-repository 'deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu xenial/'
    - sudo apt-get update -qq
    - sudo apt-get upgrade -qq -y
    - sudo apt-get dist-upgrade -qq -y
    - sudo apt-get install -qq puppet-agent -y
    - sudo apt-get install -qq git -y
    - sudo apt-get install -qq libxml2-utils -y
    - sudo apt-get install -qq libxml2-dev -y
    - sudo apt-get install -qq libssl-dev -y
    - sudo apt-get install -qq libgit2-dev -y
    - sudo apt-get install -qq r-base r-base-dev -y
    - sudo apt-get install -qq libcurl4-openssl-dev -y
    - sudo apt-get install -qq iptables-persistent -y
    - sudo apt-get install -qq mysql-server -y
    - sudo apt-get install -qq mysql-client -y
    - sudo apt-get install -qq libcurl4-openssl-dev -y
    - sudo apt-get install -qq opal -y
    - sudo /opt/puppetlabs/puppet/bin/gem install r10k
    - git clone -b ubuntu16 https://github.com/StuartWheater/datashield-infrastructure.git /tmp/datashield-infrastructure
    - sudo gem install r10k
#    - ls /opt/puppetlabs/puppet/bin/
#    - sudo find / -name r10k

install:
    - cd /tmp/datashield-infrastructure/puppet/environments/datashield_travis && sudo /home/travis/.rvm/gems/ruby-2.4.1/gems/r10k-2.6.4/bin/r10k puppetfile install && cd --
    - sudo /opt/puppetlabs/bin/puppet apply /tmp/datashield-infrastructure/puppet/environments/datashield_travis/manifests/site.pp --environment datashield_travis --environmentpath /tmp/datashield-infrastructure/puppet/environments 2>&1 | awk '{ print strftime("%Y-%m-%d %H:%M:%S "), $0; fflush(); }'

script:
    - sudo /tmp/travis-tool.sh install_github jimhester/covr
    - cd /home/travis/build/StuartWheater/dsClient
    - /tmp/travis-tool.sh run_tests

after_failure:
    - cd /home/travis/build/StuartWheater/dsClient && sudo /tmp/travis-tool.sh dump_logs && cd --
    - sudo cat /var/log/opal/stdout.log

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
    - Rscript -e 'covr::codecov()'
